40 enhancement netapp ontap storage snapshot policy need to support import
NetApp/terraform-provider-netapp-ontap pull request #105
Opened 2023-11-30 01:10 UTC by wenjun666

2023-12-04 21:28 UTC, chuyich commented on docs/resources/storage_snapshot_policy_resource.md
> +  terraform import netapp-ontap_storage_snapshot_policy_resource.example exp1,svm1,cluster4
"exp1" might confuse people. Maybe use something like "policy1" or "snp_policy1"

2023-12-04 21:29 UTC, chuyich commented on docs/resources/storage_snapshot_policy_resource.md
> +  id = "exp1,svm1,cluster4"
same as here "exp1" seems not really represent as the snapshot policy name (line 107 & 108)

2023-12-04 21:30 UTC, chuyich commented on docs/resources/storage_snapshot_policy_resource.md
> +# __generated__ by Terraform from "exp1,svm1,cluster4"
same as these lines 119, 120, 122

2023-12-04 21:31 UTC, chuyich commented on internal/provider/storage_snapshot_policy_test.go
> +					resource.TestCheckResourceAttr("netapp-ontap_protocols_nfs_export_policy_resource.example", "name", "tfimportpolicy"),
the resource address is not about storage policy

2023-12-04 21:33 UTC, chuyich requested changes
please check the comments and update them.

2023-12-12 20:11 UTC, carchi8py approved these changes

2023-12-12 20:29 UTC, chuyich requested changes
One more small change.

2023-12-12 20:29 UTC, chuyich commented on docs/resources/storage_snapshot_policy_resource.md
> +  to = netapp-ontap_storage_snapshot_policy_resource.exp_import
It does not match the example in line 120 (exp_import vs policy1_import)

2023-12-14 21:41 UTC, chuyich approved these changes

2023-12-19 18:42 UTC, merged