22 new data source security account
NetApp/terraform-provider-netapp-ontap pull request #114
Opened 2023-12-12 20:59 UTC by carchi8py

Adds #22

2023-12-19 19:14 UTC, chuyich commented on internal/interfaces/security_account.go
> +// TODO:
These lines can be removed.

2023-12-19 19:33 UTC, chuyich commented on internal/provider/security_account_data_source.go
> +			"owner": schema.SingleNestedAttribute{
'owner' should be required in one data source case, right?

2023-12-19 19:39 UTC, chuyich commented on internal/provider/security_accounts_data_source.go
> +// TODO:
these lines can be removed

2023-12-19 21:43 UTC, chuyich commented on docs/data-sources/security_account_data_source.md
> +- `name` (String) SecurityAccount owner name
If the user only provides "name", then it will be multiple records.

2023-12-19 21:48 UTC, chuyich requested changes
One question on the single data source: the user needs to provide name and owner info to get the single record. So owner probably needs to be required.

2023-12-19 21:50 UTC, chuyich requested changes
also missing the CHANGELOG update

2024-01-02 20:49 UTC, carchi8py commented on internal/provider/security_account_data_source.go
> +			"owner": schema.SingleNestedAttribute{
NO.... YES.....

So an account can be SVM specific or cluster specific. 

Let me try some test out, my worry here is cluster name might not be known by the user.

2024-01-19 21:23 UTC, carchi8py commented on docs/data-sources/security_account_data_source.md
> +- `name` (String) SecurityAccount owner name
I don't think there a way around that.

2024-01-19 21:24 UTC, carchi8py commented
> One question on the single data source: the user needs to provide name and owner info to get the single record. So owner probably needs to be required.

Since cluster user can't give an owner info we can't have it required.

2024-01-23 01:15 UTC, chuyich commented on scripts/acctest.sh
> +export TF_ACC_NETAPP_HOST="10.193.180.108"
Is it ok that we hard-coded these values?

2024-01-24 02:35 UTC, chuyich commented
Please resolve the conflict, then it should be good to go.

2024-01-24 02:38 UTC, chuyich approved these changes

2024-01-24 22:33 UTC, merged