added flexcache resource, data source and data sources.
NetApp/terraform-provider-netapp-ontap pull request #134
Opened 2024-02-15 06:48 UTC by wenjun666

2024-02-16 18:59 UTC, chuyich commented
The provider.tf in examples should be a link to examples/provider/provider.tf

2024-02-16 19:31 UTC, chuyich commented
Missing doc and changelog.

2024-02-20 22:41 UTC, carchi8py reviewed
You missing the documentation pages.

2024-02-20 22:41 UTC, carchi8py commented on examples/data-sources/netapp-ontap_storage_flexcache/provider.tf
> +      hostname = "10.193.176.159"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/data-sources/netapp-ontap_storage_flexcache/provider.tf
> +      hostname = "10.193.180.108"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/data-sources/netapp-ontap_storage_flexcache/provider.tf
> +      hostname = "10.193.176.186"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/data-sources/netapp-ontap_storage_flexcaches/provider.tf
> +      hostname = "10.193.176.159"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/data-sources/netapp-ontap_storage_flexcaches/provider.tf
> +      hostname = "10.193.180.108"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/data-sources/netapp-ontap_storage_flexcaches/provider.tf
> +      hostname = "10.193.176.186"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/resources/netapp-ontap_storage_flexcache/provider.tf
> +      hostname = "10.193.176.159"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/resources/netapp-ontap_storage_flexcache/provider.tf
> +      hostname = "10.193.180.108"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on examples/resources/netapp-ontap_storage_flexcache/provider.tf
> +      hostname = "10.193.176.186"
can you remove the IP address

2024-02-20 22:41 UTC, carchi8py commented on internal/provider/provider.go
> +		NewStorageFlexcacheRsource,
Can you put this in Alphabetically

2024-02-20 22:41 UTC, carchi8py commented on internal/provider/provider.go
> +		NewFlexcacheDataSource,
Can you put this in Alphabetically

2024-02-20 22:44 UTC, carchi8py commented on internal/provider/storage_flexcache_resource_test.go
> +		host = "10.193.176.186"
These to be replace with the TF_ACCversions

2024-03-07 20:35 UTC, suhasbshekar approved these changes

2024-03-15 21:32 UTC, chuyich commented on docs/data-sources/storage_flexcache_data_source.md
> +
Can you put example here?

2024-03-15 21:32 UTC, chuyich commented on docs/data-sources/storage_flexcaches_data_source.md
> +
Same here. Need example Ref. https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/docs/data-sources/cluster_data_source.md

2024-03-15 21:34 UTC, chuyich commented on docs/resources/storage_flexcache_resource.md
> +
Same here. Need example even the ONTAP commands. Ref. https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/docs/resources/cluster_licensing_license_resource.md?plain=1

2024-03-15 21:36 UTC, carchi8py requested changes

2024-03-15 21:36 UTC, carchi8py commented on docs/data-sources/storage_flexcache_data_source.md
> +subcategory: ""
storage

2024-03-15 21:36 UTC, carchi8py commented on docs/data-sources/storage_flexcaches_data_source.md
> +subcategory: ""
storage

2024-03-15 21:36 UTC, carchi8py commented on docs/data-sources/storage_flexcache_data_source.md
> +Flexcache resource
Missing an example

2024-03-15 21:36 UTC, carchi8py commented on docs/data-sources/storage_flexcaches_data_source.md
> +
Missing an example

2024-03-15 21:36 UTC, carchi8py commented on docs/resources/storage_flexcache_resource.md
> +
Missing an example

2024-03-15 21:36 UTC, carchi8py commented on internal/provider/storage_flexcache_resource_test.go
> +				),
Is it possible to have a import example.

2024-03-15 21:39 UTC, chuyich commented on internal/provider/storage_flexcache_resource.go
> +func (r *StorageFlexcacheResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
Why there is no modification for this resource

2024-03-15 21:54 UTC, chuyich requested changes
Please update the document with example section and Related ONTAP commands section. 
data source: https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/docs/data-sources/cluster_data_source.md?plain=1
resource: https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/docs/resources/cluster_licensing_license_resource.md?plain=1

Also the modification function and its acc test.

2024-03-26 22:12 UTC, wenjun666 commented on internal/provider/storage_flexcache_resource.go
> +func (r *StorageFlexcacheResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
no updates can be done on flexcache

2024-04-03 21:22 UTC, suhasbshekar approved these changes

2024-04-04 22:57 UTC, carchi8py approved these changes

2024-04-04 23:33 UTC, chuyich commented on internal/provider/storage_flexcache_resource.go
> +			"size_unit": schema.StringAttribute{
line 410 to me it's required. Or should this have a default value?

2024-04-04 23:53 UTC, chuyich commented on internal/provider/storage_flexcache_resource.go
> +			//there could be a space not enough or storage type error if the aggreates are not set
Based on the comment, then aggregate should be required, right?

2024-04-05 18:52 UTC, wenjun666 commented on internal/provider/storage_flexcache_resource.go
> +			//there could be a space not enough or storage type error if the aggreates are not set
no, it doesn't have to be. It will be auto assign it no aggregate given. But that's not guarantee to work.

2024-04-05 18:52 UTC, wenjun666 commented on internal/provider/storage_flexcache_resource.go
> +			"size_unit": schema.StringAttribute{
“If not specified in POST, the following default property values are assigned:
size - 10% of origin volume size or 1GB per constituent, whichever is greater.”

It should just let the API decides what to set if user didn't give a input.

2024-04-05 18:59 UTC, chuyich commented on internal/provider/storage_flexcache_resource.go
> +			"size_unit": schema.StringAttribute{
If so, then on line 410 needs to be adjusted. If the user does not provide size and size unit, it will be failed with on line 410. i would suggest to have an acc test with minimum configuration (without size, size unit,...) to see if that works.

2024-04-05 19:31 UTC, chuyich approved these changes

2024-04-05 19:59 UTC, merged