New resource CLuster Peers
NetApp/terraform-provider-netapp-ontap pull request #148
Opened 2024-03-08 17:53 UTC by suhasbshekar

#49

2024-03-11 18:58 UTC, carchi8py requested changes

2024-03-11 18:58 UTC, carchi8py commented on examples/resources/netapp-ontap_cluster_peers/resource.tf
> +    ip_addresses = ["10.193.180.110"]
Can you replace these IP adress with something like 10.10.10.10

2024-03-11 18:58 UTC, carchi8py commented on docs/resources/cluster_peers_resource.md
> +    "10.193.180.110"
same thing here replace the ip with something like 10.10.10.10

2024-03-13 23:28 UTC, wenjun666 approved these changes

2024-03-15 21:29 UTC, carchi8py approved these changes

2024-03-15 21:29 UTC, merged