27 new resource protocolscifsshares
NetApp/terraform-provider-netapp-ontap pull request #165
Opened 2024-04-07 01:50 UTC by wenjun666

2024-04-19 17:11 UTC, suhasbshekar requested changes

2024-04-19 17:11 UTC, suhasbshekar commented on docs/resources/protocols_cifs_share_resource.md
> +subcategory: "protocols"
protocols -> Protocols

2024-04-23 16:58 UTC, carchi8py approved these changes

2024-04-23 17:27 UTC, chuyich commented on internal/provider/protocols_cifs_share_resource.go
> +				Optional: true,
It seems "path" is required. Can you double check if path is required?

2024-04-23 17:29 UTC, suhasbshekar approved these changes

2024-04-23 17:35 UTC, chuyich commented
I would suggest to have a acc test which only uses minimum configuration to make sure it works as expected.

2024-04-23 17:41 UTC, merged