Edit cluster data source.
NetApp/terraform-provider-netapp-ontap pull request #166
Opened 2024-04-09 04:07 UTC by wenjun666

2024-04-10 17:55 UTC, suhasbshekar requested changes

2024-04-10 17:55 UTC, suhasbshekar commented on internal/provider/cluster_data_source.go
> +			// "password": schema.StringAttribute{
comments needed?

2024-04-10 21:53 UTC, carchi8py commented on docs/data-sources/cluster_data_source.md
> +subcategory: "cluster"
Should be Cluster

2024-04-16 17:16 UTC, suhasbshekar approved these changes

2024-04-16 22:31 UTC, merged