210 enhancement update examples with new data source and resource name
NetApp/terraform-provider-netapp-ontap pull request #211
Opened 2024-05-22 06:58 UTC by chuyich

fix #210

2024-05-22 18:26 UTC, suhasbshekar approved these changes

2024-05-29 19:38 UTC, carchi8py requested changes

2024-05-29 19:38 UTC, carchi8py commented on docs/data-sources/protocols_cifs_local_group_data_source.md
> -page_title: "netapp-ontap_protocols_cifs_local_group_data_source Data Source - terraform-provider-netapp-ontap"
Protocols need to be removed

2024-05-29 19:38 UTC, carchi8py commented on docs/data-sources/protocols_cifs_local_group_data_source.md
> -data "netapp-ontap_protocols_cifs_local_group_data_source" "local_group" {
Protocols need to be removed

2024-05-29 19:38 UTC, carchi8py commented on docs/resources/storage_aggregate_resource.md
> +resource "netapp-ontap_storage_aggregate" "example" {
Storage need to be removed.

2024-05-29 19:39 UTC, carchi8py commented
Protocols and storage need to be removed (we shorted those names.

2024-05-29 19:58 UTC, chuyich commented
@carchi8py Do those shorted names also applied to both data source and resource? Then the directories of the examples need to be updated accordingly.

2024-05-31 15:51 UTC, carchi8py approved these changes

2024-05-31 15:51 UTC, merged