140 new resource securityroles
NetApp/terraform-provider-netapp-ontap pull request #226
Opened 2024-06-04 04:40 UTC by wenjun666

2024-06-13 17:13 UTC, chuyich commented on internal/provider/security/security_role_data_source.go
> +// TODO:
Can you remove TODO?

2024-06-13 17:19 UTC, chuyich commented on internal/interfaces/security_role.go
> +// TODO:
Same here: remove TODO

2024-06-13 17:20 UTC, chuyich commented on internal/interfaces/security_role.go
> +	// if svmName == "" {
What are these comments for? Can they be removed?

2024-06-13 17:24 UTC, chuyich commented
For the data source, just wondered those "optional" parameters in the schema should be "computed". Can you double check?

2024-06-17 20:03 UTC, suhasbshekar requested changes
CHANGELOG?

2024-07-12 15:42 UTC, carchi8py requested changes
Remove data source from the names completely in all places.

2024-07-12 15:42 UTC, carchi8py commented on docs/data-sources/security_role_data_source.md
> +data "netapp-ontap_security_role_data_source" "security_role" {
Remove data_source

2024-07-12 15:42 UTC, carchi8py commented on docs/data-sources/security_role_data_source.md
> +page_title: "netapp-ontap_security_role_data_source Data Source - terraform-provider-netapp-ontap"
data_source

2024-07-12 15:42 UTC, carchi8py commented on docs/data-sources/security_roles_data_source.md
> +page_title: "netapp-ontap_security_roles_data_source Data Source - terraform-provider-netapp-ontap"
data_source

2024-07-12 15:42 UTC, carchi8py commented on docs/data-sources/security_roles_data_source.md
> +data "netapp-ontap_security_roles_data_source" "security_roles" {
data_source

2024-07-22 22:20 UTC, chuyich commented
Missing the examples

2024-08-05 21:54 UTC, carchi8py commented
What do we need to get this merged in?

2024-08-08 16:23 UTC, chuyich requested changes

2024-08-08 16:23 UTC, chuyich commented on CHANGELOG.md
> +* **New Data Source:** `netapp-ontap_security_role` ([#139](https://github.com/NetApp/terraform-provider-netapp-ontap/issues/139))
Missing netapp-ontap_security_roles. here.

2024-08-13 22:51 UTC, wenjun666 commented
> For the data source, just wondered those "optional" parameters in the schema should be "computed". Can you double check?

Yes, should be "computed."

2024-08-14 21:26 UTC, suhasbshekar requested changes
Looking good, just a TODO to be removed

2024-08-14 21:26 UTC, suhasbshekar commented on internal/provider/security/security_roles_data_source.go
> +// delete these 5 lines
can you remove the TODO?

2024-08-19 20:21 UTC, carchi8py requested changes
Can you make the change @suhasbshekar requested.

2024-08-20 18:34 UTC, carchi8py approved these changes

2024-08-20 22:24 UTC, chuyich approved these changes

2024-08-21 21:28 UTC, suhasbshekar approved these changes

2024-08-28 19:19 UTC, merged