new data source quota rules
NetApp/terraform-provider-netapp-ontap pull request #260
Opened 2024-08-05 22:06 UTC by suhasbshekar

#135

2024-08-05 22:09 UTC, carchi8py requested changes

2024-08-05 22:09 UTC, carchi8py commented on docs/data-sources/storage_quota_rule_data_source.md
> +StorageQuotaRule data source
change this name no storage (same thing on lines 6)

2024-08-05 22:09 UTC, carchi8py commented on docs/data-sources/storage_quota_rules_data_source.md
> +  StorageQuotaRules data source
change this name (no storage), same on line 11

2024-08-07 22:27 UTC, carchi8py approved these changes

2024-08-08 16:12 UTC, chuyich commented on CHANGELOG.md
> +* **New Data Source:** `netapp-ontap_quota_rules` ([#135](https://github.com/NetApp/terraform-provider-netapp-ontap/issues/135))
Just a nitpick. Based on what we have, the data source and resource are grouped together. 
So this line should be moved up to line 5.

2024-08-08 16:20 UTC, chuyich commented on CHANGELOG.md
> +* **New Data Source:** `netapp-ontap_quota_rule` ([#135](https://github.com/NetApp/terraform-provider-netapp-ontap/issues/135))
Same as this line. Data source should be grouped together.

2024-08-13 23:32 UTC, merged