Add AWS Lambda.
NetApp/terraform-provider-netapp-ontap pull request #262
Opened 2024-08-08 05:30 UTC by wenjun666

2024-08-08 23:02 UTC, carchi8py requested changes

2024-08-08 23:02 UTC, carchi8py commented on internal/provider/provider.go
> +							MarkdownDescription: "Indicates a preference order between several routes to the same destination.",
not sure what this means?

2024-08-13 23:10 UTC, suhasbshekar requested changes

2024-08-13 23:10 UTC, suhasbshekar commented on internal/restclient/rest_response.go
> +	// }
can you remove the commented code ?

2024-08-19 20:17 UTC, carchi8py approved these changes

2024-08-19 20:47 UTC, carchi8py requested changes

2024-08-19 20:47 UTC, carchi8py commented on internal/provider/provider.go
> +								"lambda": schema.SingleNestedAttribute{
Change to Just Aws

2024-08-20 15:32 UTC, chuyich commented
The lint issue can be resolved after the PR sync with the latest integration/main branch.

2024-08-20 15:43 UTC, chuyich commented
Missing CHANGELOG

2024-08-20 15:47 UTC, chuyich requested changes
Missing CHANGELOG and documentation.

2024-08-20 18:30 UTC, carchi8py reviewed
Looks good can you make the change to remove commented out code that @suhasbshekar mentioned.

2024-08-28 19:18 UTC, carchi8py commented on CHANGELOG.md
> +* **provider**: add `aws_lambda` option. ([#262](https://github.com/NetApp/terraform-provider-netapp-ontap/issues/262))
Can you put this under features and at the top

2024-08-29 18:25 UTC, carchi8py requested changes

2024-08-29 18:25 UTC, carchi8py commented on CHANGELOG.md
> +* **netapp-ontap_security_account**: Add support for import and update ([#243](https://github.com/NetApp/terraform-provider-netapp-ontap/issues/243)
missing a 
)
at the end of the line

2024-09-03 18:16 UTC, suhasbshekar approved these changes

2024-09-03 22:05 UTC, carchi8py approved these changes

2024-09-03 22:10 UTC, carchi8py requested changes
You need to update doc/index.html with the documentation for the new variables.

2024-09-09 12:24 UTC, carchi8py approved these changes

2024-09-10 17:36 UTC, chuyich approved these changes

2024-09-10 18:35 UTC, merged