140 new resource securityroles 1
NetApp/terraform-provider-netapp-ontap pull request #275
Opened 2024-08-26 23:55 UTC by wenjun666

2024-08-28 19:20 UTC, carchi8py approved these changes

2024-08-29 22:02 UTC, chuyich requested changes

2024-08-29 22:02 UTC, chuyich commented on CHANGELOG.md
>  * **New Data Source:** `netapp-ontap_security_login_message` ([#17](https://github.com/NetApp/terraform-provider-netapp-ontap/issues/17))
Missing the resource of security_role

2024-08-29 22:02 UTC, chuyich commented on docs/resources/security_role.md
> +- `query` (String) Optional attribute that can be specified only if the 'path' attribute refers to a command/command directory path. The privilege tuple implicitly defines a set of objects the role c
Missing the import part

2024-08-30 19:01 UTC, suhasbshekar requested changes

2024-08-30 19:01 UTC, suhasbshekar commented on docs/resources/security_role.md
> +  ]
intendation

2024-08-30 19:01 UTC, suhasbshekar commented on examples/resources/netapp-ontap_security_role/resource.tf
> +	}
indentation

2024-09-03 16:02 UTC, wenjun666 commented on docs/resources/security_role.md
> +- `query` (String) Optional attribute that can be specified only if the 'path' attribute refers to a command/command directory path. The privilege tuple implicitly defines a set of objects the role c
what about the import part?

2024-09-06 00:18 UTC, chuyich requested changes
Besides the commented parts. Maybe add the change based on agreed resource naming? Or do it later is ok, too.

2024-09-06 00:18 UTC, chuyich commented on docs/resources/security_role.md
> +subcategory: ""
Missing subcatetory

2024-09-06 00:18 UTC, chuyich commented on docs/resources/security_role.md
> +
Missing supported platforms

2024-09-10 18:16 UTC, suhasbshekar approved these changes

2024-09-11 21:09 UTC, chuyich reviewed
Wondered if query is part of the privilege in this resource. Please double check it.

2024-09-11 22:14 UTC, wenjun666 commented
> Wondered if query is part of the privilege in this resource. Please double check it.

I don't think it matters, as query is privilege.query, if API returns nothing of query, the struct will omit empty.

2024-09-13 00:33 UTC, chuyich approved these changes

2024-09-16 19:48 UTC, merged