82 new resource storageqtrees
NetApp/terraform-provider-netapp-ontap pull request #280
Opened 2024-08-29 21:08 UTC by wenjun666

2024-08-29 22:19 UTC, chuyich requested changes

2024-08-29 22:19 UTC, chuyich commented on docs/resources/storage_qtrees.md
> +- `path` (String) Client visible path to the qtree. This field is not available if the volume does not have a junction-path configured.
Missing import part

2024-08-29 22:19 UTC, chuyich commented on internal/provider/storage/storage_qtrees_resource_test.go
> +					resource.TestCheckResourceAttr("netapp-ontap_storage_qtree.example", "name", "acc_test_qtree"),
resource name is not aligned, same as the rest of the tests - missing s

2024-08-29 22:19 UTC, chuyich commented on internal/provider/storage/storage_qtrees_data_source.go
> +// TODO:
Remove these lines

2024-09-05 23:46 UTC, chuyich requested changes
Missing data source examples

2024-09-09 12:26 UTC, carchi8py approved these changes

2024-09-09 17:07 UTC, wenjun666 commented
> Missing data source examples

Yes, added back in.

2024-09-10 18:17 UTC, suhasbshekar approved these changes

2024-09-10 18:48 UTC, chuyich approved these changes

2024-09-10 20:08 UTC, merged