Renamed networking folders.
NetApp/terraform-provider-netapp-ontap pull request #288
Opened 2024-09-10 20:30 UTC by wenjun666

2024-09-11 20:12 UTC, suhasbshekar approved these changes

2024-09-16 20:00 UTC, chuyich requested changes
Do we need to change the directory name under the provider from networking to network since the API is network/ip/interfaces and network/ip/route?
Also the file name under internal/interface: networking_xx to network_xxx?

2024-09-16 20:00 UTC, chuyich commented on docs/resources/network_ip_interfaces_resource.md
>  !> The terraform import CLI command can only import resources into the state. Importing via the CLI does not generate configuration. If you want to generate the accompanying configuration for importe
Can you remove !> here?

2024-09-16 20:58 UTC, chuyich approved these changes
the doc comment can be ignored since the syntax is slightly different between github and terraform registry.

2024-09-17 18:45 UTC, closed without merging