[Enhancement]: Add SVM `storage_limit` parameter
NetApp/terraform-provider-netapp-ontap pull request #328
Opened 2024-10-16 10:02 UTC by acch

Adds ability to configure `storage_limit` parameter of SVM.

Closes #302 .

Acceptance tests pass:
```shell
$ TF_ACC=1 go test ./internal/provider/svm/svm_resource_test.go -v
=== RUN   TestAccSvmResource
--- PASS: TestAccSvmResource (33.36s)
PASS
ok      command-line-arguments  33.367s
```

Example Terraform Configuration:
```terraform
// sample SVM with storage_limit parameter
resource "netapp-ontap_svm" "example" {
  cx_profile_name = ...
  name            = ...
  ...
  storage_limit   = "4294967296"
}
```

2024-10-29 20:47 UTC, carchi8py commented
@acch  before we can accept this we need you to follow this (https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/CONTRIBUTING.md). I think the only steps missing right now is step 5.

2024-10-30 08:46 UTC, acch commented
@carchi8py I had signed the NetApp CCLA on Oct 16... please let me know what's missing.

2024-10-31 21:17 UTC, carchi8py commented
@acch thank i have that now. Look like the email group we were using was not accepting External email so we didn't get a copy. We've fix that and have your CCLA.

2024-10-31 21:18 UTC, carchi8py commented
We have a major version 2.0 that in the final stages of our legal review. 

We will be adding this in to our 2.1 release which will be the release after that one.

2024-12-17 16:23 UTC, carchi8py commented
@acch  Happy Holidays, just a head up we will be reviewing this shorting. Sorry for the hold up we were waiting on Security to finish their review of 2.0 before releasing it and that ended up taking significantly longer than we had hope. Now that, that out of the way we are starting to merge thing in again. Right now I'm working on getting all the dependencies updated and then we'll start review these.

Probably will have review the first week of Jan (or end of this week if I have time).

2024-12-22 13:46 UTC, acch commented
Happy Holidays @carchi8py! Thanks for the update.
I'll be back in the office the first week of Jan., and will check if anything needs rebasing...

Please let me know what I can do to help.

Thanks much for all your efforts — enjoy a few days off! 🎄

2025-01-02 16:42 UTC, chuyich commented
@acch Since storage_limit is the new field and only supported 9.13 or higher, please update the support platform section on the document of data source and resource under docs.
Also, the version check has to be done. You may check [this](https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/internal/interfaces/snapmirror_policy.go#L171) as a reference.

2025-01-02 16:43 UTC, chuyich requested changes
Please update doc and add version check.

2025-01-06 14:25 UTC, acch commented
Hello @chuyich, thank you very much for reviewing this PR.

I have updated the docs and added cluster version checks to `GetSvmByName*()`. Acceptance tests (still) pass.
Please let me know if this is acceptable, or what is missing.

Thanks much!

2025-01-06 17:34 UTC, carchi8py requested changes

2025-01-06 17:34 UTC, carchi8py commented on docs/data-sources/svm_data_source.md
> +  * `storage_limit` attribute supported with ONTAP system 9.13 or higher
This needs to be added in the list of attributes on line 37-46

2025-01-06 17:34 UTC, carchi8py commented on docs/data-sources/svms_data_source.md
> +  * `storage_limit` attribute supported with ONTAP system 9.13 or higher
This needs to be added in the list of attributes on line 64-72

2025-01-06 17:34 UTC, carchi8py commented on docs/resources/svm_resource.md
> +  * `storage_limit` attribute supported with ONTAP system 9.13 or higher
This needs to be added in the list of attributes on line 47-63

2025-01-06 19:50 UTC, chuyich requested changes

2025-01-06 19:50 UTC, chuyich commented on internal/provider/svm/svm_resource.go
> +				Default:             int64default.StaticInt64(0),
It is an optional parameter based on the API doc https://docs.netapp.com/us-en/ontap-restapi-9131/ontap/post-svm-svms.html#recommended-optional-properties
The default value is not needed.

2025-01-06 19:50 UTC, chuyich commented on internal/interfaces/svm.go
> +	Storage        Storage             `mapstructure:"storage"`
Since it's optional, it should be set omitempty.

2025-01-07 08:50 UTC, acch commented on internal/provider/svm/svm_resource.go
> +				Default:             int64default.StaticInt64(0),
Without a default value, the attribute remains "unknown" after the apply - resulting in the following error:

```
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for netapp-ontap_svm.example.storage_limit. All values must be known after apply, so this is
│ always a bug in the provider and should be reported in the provider's own repository. Terraform will still save the other known object values in the state.
╵
```

I could manually set the value to 0 in `internal/provider/svm/svm_resource.go > Create()`, but isn't a default value in the schema definition easier to understand?

2025-01-07 09:03 UTC, acch commented on internal/interfaces/svm.go
> +	Storage        Storage             `mapstructure:"storage"`
OK, I did mark the optional `storage` and (nested) `limit` params as 'omitempty'. However, there's some code in place to delete empty params from the request body, which I've adapted to... don't think 'omitempty' will make any difference.

https://github.com/acch/terraform-provider-netapp-ontap/blob/ceeb032a1923209353296a28db20468801db729d/internal/interfaces/svm.go#L221-L232

```go
	if setAggrEmpty {
		delete(body, "aggregates")
	}
	if setCommentEmpty {
		delete(body, "comment")
	}
	if setStorageLimitEmpty {
		// delete storage.limit from request body, so that ONTAP uses default value
		if v, ok := body["storage"].(map[string]interface{}); ok {
			delete(v, "limit")
		}
	}
```

2025-01-07 09:05 UTC, acch commented
Thanks @carchi8py and @chuyich for your feedback!

I've added the `storage_limit` argument to the docs. I was under the impression that these lists are generated automatically, due to the `schema generated by tfplugindocs` comment... Now understand that they need to be updated manually.

I've also marked the optional params as 'omitempty', and did verify that acceptance tests (still) pass.
Please let me know if this is acceptable, or what is missing.

Thanks much!

2025-01-21 15:07 UTC, carchi8py commented
@acch sorry for the late response, i was out last week with a small family emergency.

We will need you to rebase all your pull requests. There was a security issue that required us to rewrite the git history that we made last week. Because of this any pull request or Fork that hasn't rebased is going to appear as all files have been modified. Can you please rebase your pull request.

2025-01-22 13:25 UTC, acch commented
@carchi8py Sure, I just rebased all PR's.

For our internal planning: how much more time do you think will be required to incorporate our changes into a release available from Terraform registry? Is there already a (rough) target for the 2.1 release?

2025-01-22 21:53 UTC, suhasbshekar approved these changes

2025-01-23 16:53 UTC, carchi8py commented
@acch we don't have a rough date for a release. Let me talk to the team.

But we don't have any hard requirement for 2.1 so we should be able to make 2.1 just your 6 pull request once there merge in and anything move everything else to 2.2.

2025-01-23 23:23 UTC, carchi8py approved these changes

2025-01-31 18:31 UTC, acch commented
@carchi8py Are we good to merge this PR?

Please let me know what I need to do exactly to have the PRs added to the provider. My understanding is that I've addressed all requested changes... please let me know what's missing.

Many thanks!

2025-01-31 19:20 UTC, chuyich commented on internal/provider/svm/svm_resource.go
> +				Default:             int64default.StaticInt64(0),
You may use 				
```
        PlanModifiers: []planmodifier.Int64{
              IntUseStateForUnknown(),
       },
```
ref. https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/internal/provider/storage/storage_aggregate_resource.go#L159 and see how to handle this parameter in creation/read/update. Since it's optional in the API call, the default value does not have to be set.

2025-01-31 19:33 UTC, chuyich commented on internal/interfaces/svm.go
> +	Storage        Storage             `mapstructure:"storage"`
You may check https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/internal/provider/storage/storage_volume_resource.go#L647

2025-02-03 09:15 UTC, acch commented on internal/provider/svm/svm_resource.go
> +				Default:             int64default.StaticInt64(0),
Understood. I have removed the default value, and `omitempty` removes the parameter from the request body if unset.

I've adapted the same logic as in [StorageVolumeResource.PercentSnapshotSpace](https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/internal/provider/storage/storage_volume_resource.go#L647).
Please let me know if this is acceptable.

2025-02-03 09:16 UTC, acch commented on internal/interfaces/svm.go
> +	Storage        Storage             `mapstructure:"storage"`
Understood. I have removed the explicit `setStorageLimitEmpty` parameter, and instead adapted the same logic as in [StorageVolumeResource.PercentSnapshotSpace](https://github.com/NetApp/terraform-provider-netapp-ontap/blob/integration/main/internal/provider/storage/storage_volume_resource.go#L647).
Please let me know if this is acceptable.

2025-02-03 17:36 UTC, suhasbshekar requested changes
Can you fix the lint issues in checks below?

2025-02-03 20:22 UTC, suhasbshekar commented
Can you update CHANGELOG.md file?

Also your branch is behind the integration/main, we added few more checks to the pipeline as it was missing here, since your PR is from a fork of this repo, so could you pull the new changes into your branch and update the PR?

Just for our reference, since we have disabled ACC tests as our testing profiles are down, acc tests are passing for this PR when tested locally.

2025-02-04 08:28 UTC, acch commented
@suhasbshekar Thanks for your feedback.

- I've added the version param to `internal/interfaces/svm_test.go`, this should silence the linter error
- I've added an entry to `CHANGELOG.md`
- I've rebased my branch to `integration/main` (once again)

Acc tests are passing on my local test system (ONTAP Select running 9.15.1P4):

```shell
$ date && TF_ACC=1 go test ./internal/provider/svm/svm_resource_test.go -v && date
Tue Feb  4 08:24:24 UTC 2025
=== RUN   TestAccSvmResource
--- PASS: TestAccSvmResource (29.70s)
PASS
ok      command-line-arguments  29.714s
Tue Feb  4 08:24:54 UTC 2025
```

Please let me know what else is needed.
Many thanks!

2025-02-05 20:52 UTC, suhasbshekar commented
Please resolve the conflicts.

2025-02-06 19:02 UTC, acch commented
@suhasbshekar I've rebased the PR once again.

Can you please let me know when you'll be able to merge these changes?

2025-02-06 19:25 UTC, suhasbshekar approved these changes

2025-02-06 19:26 UTC, suhasbshekar commented
Will start merging this week, probably will have a release by next week

2025-02-06 19:27 UTC, merged