[New Resource]: Broadcast Domain
NetApp/terraform-provider-netapp-ontap pull request #333
Opened 2024-11-04 18:30 UTC by acch

Adds ability to create broadcast domains.

Closes #303.

Example Terraform Configuration:
```terraform
// sample broadcast domain with required properties
resource "netapp-ontap_network_broadcast_domain" "example" {
  cx_profile_name = "cluster1"
  ipspace         = "Default"
  name            = "bd1"
  mtu             = "1500"
}
```

2025-01-06 17:42 UTC, carchi8py requested changes
Looks good. Only thing missing is the documentation pages.

2025-01-08 14:22 UTC, acch commented
Thanks @carchi8py for your feedback!

I've manually added the documentation pages in the `docs/` directory. This is very tedious; isn't it possible to generate the docs automatically? The TF scaffolding template contains scripts for that ([here](https://github.com/hashicorp/terraform-provider-scaffolding-framework/blob/main/tools/tools.go)), but I see that you've removed them...

2025-02-01 06:59 UTC, acch commented
@carchi8py Are we good to merge this PR?

Please let me know what I need to do exactly to have the PRs added to the provider. My understanding is that I've addressed all requested changes... please let me know what's missing.

Many thanks!

2025-02-03 19:00 UTC, suhasbshekar commented
Can you update CHANGELOG.md file?

Also your branch is behind the integration/main, we added few more checks to the pipeline as it was missing here, since your PR is from a fork of this repo, so could you pull the new changes into your branch and update the PR?

Just for our reference, since we have disabled ACC tests as our testing profiles are down, acc tests are passing for this PR when tested locally.

2025-02-04 09:27 UTC, acch commented
@suhasbshekar Thanks for your feedback.

- I've added an entry to CHANGELOG.md
- I've rebased my branch to integration/main (once again)

Acc tests are passing on my local test system (ONTAP Select running 9.15.1P4):

```shell
$ date && TF_ACC=1 go test ./internal/provider/networking/network_broadcast_domain_resource_test.go -v && date
Tue Feb  4 09:26:22 UTC 2025
=== RUN   TestAccNetworkBroadcastDomainResource
--- PASS: TestAccNetworkBroadcastDomainResource (3.65s)
PASS
ok      command-line-arguments  3.657s
Tue Feb  4 09:26:26 UTC 2025
```

Please let me know what else is needed.
Many thanks!

2025-02-05 20:52 UTC, suhasbshekar commented
Please resolve the conflicts.

2025-02-06 19:03 UTC, acch commented
@suhasbshekar I've rebased the PR once again.

Can you please let me know when you'll be able to merge these changes?

2025-02-06 23:27 UTC, suhasbshekar commented
Conflicts for this PR

2025-02-07 18:24 UTC, suhasbshekar approved these changes

2025-02-07 18:27 UTC, merged