[New Resource]: Ethernet Port
NetApp/terraform-provider-netapp-ontap pull request #334
Opened 2024-11-13 10:46 UTC by acch

Adds ability to create ethernet ports (VLAN / LAG).

Closes #304.

Acceptance tests WIP.

Example Terraform Configuration:

2025-01-06 17:47 UTC, carchi8py requested changes
Looks good as well just missing documentation files.

2025-01-13 10:20 UTC, acch commented
Thanks @carchi8py for your feedback!

I've manually added the documentation pages in the `docs/` directory.

2025-02-01 07:00 UTC, acch commented
@carchi8py Are we good to merge this PR?

Please let me know what I need to do exactly to have the PRs added to the provider. My understanding is that I've addressed all requested changes... please let me know what's missing.

Many thanks!

2025-02-03 19:00 UTC, suhasbshekar commented
Can you update CHANGELOG.md file?

Also your branch is behind the integration/main, we added few more checks to the pipeline as it was missing here, since your PR is from a fork of this repo, so could you pull the new changes into your branch and update the PR?

2025-02-04 09:38 UTC, acch commented
@suhasbshekar Thanks for your feedback.

- I've added an entry to CHANGELOG.md
- I've rebased my branch to integration/main (once again)

Acc tests are passing on my local test system (ONTAP Select running 9.15.1P4):

```shell
$ date && TF_ACC=1 go test ./internal/provider/networking/network_ethernet_port_resource_test.go -v && date
Tue Feb  4 09:36:52 UTC 2025
=== RUN   TestAccNetworkEthernetPortResource
--- PASS: TestAccNetworkEthernetPortResource (15.37s)
PASS
ok      command-line-arguments  15.375s
Tue Feb  4 09:37:08 UTC 2025
```

Please let me know what else is needed.
Many thanks!

2025-02-05 20:51 UTC, suhasbshekar commented
Please resolve the conflicts.

2025-02-06 19:03 UTC, acch commented
@suhasbshekar I've rebased the PR once again.

Can you please let me know when you'll be able to merge these changes?

2025-02-07 18:27 UTC, suhasbshekar commented
Conflicts

2025-02-07 19:15 UTC, acch commented
Resolved

2025-02-07 21:55 UTC, suhasbshekar approved these changes

2025-02-10 22:51 UTC, merged