Add interface `location.broadcast_domain` parameter
NetApp/terraform-provider-netapp-ontap pull request #337
Opened 2024-11-20 13:19 UTC by acch

Adds ability to configure `location.broadcast_domain` parameter of IP Interfaces.

Closes #305.

Acceptance tests WIP:
```shell
$ TF_ACC=1 go test ./internal/provider/networking/network_ip_interface_resource_test.go -v
...
```
```shell
$ TF_ACC=1 go test ./internal/provider/networking/network_ip_interface_resource_alias_test.go -v
...
```

Example Terraform Configuration WIP:
```terraform
...
```

2025-01-06 17:58 UTC, carchi8py requested changes
Looks good as well just missing the documentation updates.

2025-01-06 17:58 UTC, carchi8py commented on internal/provider/networking/network_ip_interface_resource.go
> +							"id": schema.StringAttribute{
We typically don't have UUID in resources other than the top level one. As we only expect users to know the names and not the internal ID.

We do the top level one as computed as we do need a unique value for terraform. 

So this ID can probably be removed for the Resouce. (For the data source it can stay)

2025-01-13 10:41 UTC, acch commented on internal/provider/networking/network_ip_interface_resource.go
> +							"id": schema.StringAttribute{
The ID is optional, so users don't need to use it. However, referencing a broadcast domain by ID has the following advantage: the ID is computed by the `broadcast_domain` resource, it is "unknown" during plan-phase and only has a known value after the broadcast domain exists. Hence, Terraform implicitly understands that the `broadcast_domain` resource needs to be created first, and the interface can only be created *after* the `broadcast_domain`. When referencing a `broadcast_domain` by name, users would need to explicitly add this dependency with the `depends_on` meta-argument.

Hence, I'd suggest to keep the UUID as an optional attribute - do you agree?

2025-01-13 12:12 UTC, acch commented
Thanks @carchi8py for your feedback!

I've added the `location.broadcast_domain` argument to the docs. Please let me know what else is missing.

2025-02-01 07:01 UTC, acch commented
@carchi8py Are we good to merge this PR?

Please let me know what I need to do exactly to have the PRs added to the provider. My understanding is that I've addressed all requested changes... please let me know what's missing.

Many thanks!

2025-02-03 19:00 UTC, suhasbshekar commented
Can you update CHANGELOG.md file?

Also your branch is behind the integration/main, we added few more checks to the pipeline as it was missing here, since your PR is from a fork of this repo, so could you pull the new changes into your branch and update the PR?

2025-02-04 10:05 UTC, acch commented
@suhasbshekar Thanks for your feedback.

- I've added an entry to CHANGELOG.md
- I've rebased my branch to integration/main (once again)

Acc tests are passing on my local test system (ONTAP Select running 9.15.1P4):

```shell
$ date && TF_ACC=1 go test ./internal/provider/networking/network_ip_interface_resource_test.go -v && date
Tue Feb  4 10:03:55 UTC 2025
=== RUN   TestAccNetworkIpInterfaceResource
--- PASS: TestAccNetworkIpInterfaceResource (7.16s)
PASS
ok      command-line-arguments  7.164s
Tue Feb  4 10:04:03 UTC 2025
```

Please let me know what else is needed.
Many thanks!

2025-02-05 20:51 UTC, suhasbshekar commented
Please resolve the conflicts.

2025-02-06 19:04 UTC, acch commented
@suhasbshekar I've rebased the PR once again.

Can you please let me know when you'll be able to merge these changes?

2025-02-10 22:53 UTC, suhasbshekar approved these changes

2025-02-10 22:57 UTC, merged