Add SVM QoS Policy Activation
NetApp/terraform-provider-netapp-ontap pull request #346
Opened 2024-12-03 18:41 UTC by acch

Adds ability to configure `qos_policy` parameter of SVMs.

Closes #301.

Acceptance tests WIP:
```shell
```

Example Terraform Configuration WIP:
```terraform
```

2025-01-06 18:10 UTC, carchi8py reviewed
So do you expect users to ever pass in the UUID vs name?

When we wrote the Ansible/Terraform modules/resource, we've already assume users would always use name, and we would treat UUID as more of a internal thing. As a user is having both name and UUID useful?

2025-01-07 19:19 UTC, suhasbshekar requested changes

2025-01-07 19:19 UTC, suhasbshekar commented on internal/provider/svm/svm_qos_policy_activation_resource.go
> +					"id": schema.StringAttribute{
We try to use name all the time, as UUID is not something user friendly, and name itself can handle all functionality, so we have used name in all our Ansible/Terrafrom modules/resources. Unless you have an explicit case, let us know

2025-01-13 10:57 UTC, acch commented
There is an advantage of referencing dependent resources by their UUID: the ID is computed by ONTAP API, and hence it's "unknown" during plan-phase. Terraform uses this information when building its dependency graph, and implicitly understands that the dependent resources (e.g. `svm` or `qos_policy`) must be created *first*, before the `svm_qos_policy_activation` resource.

When referencing resources by their name, Terraform has no indication that one resource depends on the existence of another, and thus needs to be created first. It would attempt to create all resources in parallel (race condition). To prevent this, one would need to add the `depends_on` meta-argument.

So the following code...

```terraform
resource "netapp-ontap_qos_policy" "this" {
  name = "test"
}
resource "netapp-ontap_svm_qos_policy_activation" "this" { 
  qos_policy = {
    id = netapp-ontap_qos_policy.this.id
  }
}
```

...is equivalent to the following code:

```terraform
resource "netapp-ontap_qos_policy" "this" {
  name = "test"
}
resource "netapp-ontap_svm_qos_policy_activation" "this" { 
  qos_policy = {
    name = "test"
  }
  depends_on = [ netapp-ontap_qos_policy.this ]
}
```

Hence, I'd suggest to keep the UUID as an optional attribute - do you agree?

2025-01-13 14:52 UTC, acch commented
I've manually added the documentation pages in the `docs/` directory. Please let me know what else is missing.

2025-02-01 07:02 UTC, acch commented
@carchi8py Are we good to merge this PR?

Please let me know what I need to do exactly to have the PRs added to the provider. My understanding is that I've addressed all requested changes... please let me know what's missing.

Many thanks!

2025-02-03 19:01 UTC, suhasbshekar commented
Can you update CHANGELOG.md file?

Also your branch is behind the integration/main, we added few more checks to the pipeline as it was missing here, since your PR is from a fork of this repo, so could you pull the new changes into your branch and update the PR?

2025-02-04 10:18 UTC, acch commented
@suhasbshekar Thanks for your feedback.

- I've added an entry to CHANGELOG.md
- I've rebased my branch to integration/main (once again)

Acc tests are passing on my local test system (ONTAP Select running 9.15.1P4):

```shell
$ date && TF_ACC=1 go test ./internal/provider/svm/svm_qos_policy_activation_resource_test.go -v && date
Tue Feb  4 10:18:03 UTC 2025
=== RUN   TestAccSvmQosPolicyActivationResource
--- PASS: TestAccSvmQosPolicyActivationResource (2.41s)
PASS
ok      command-line-arguments  2.421s
Tue Feb  4 10:18:06 UTC 2025
```

Please let me know what else is needed.
Many thanks!

2025-02-04 19:06 UTC, suhasbshekar requested changes

2025-02-04 19:06 UTC, suhasbshekar commented on internal/provider/svm/svm_qos_policy_activation_resource_test.go
> +	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
can you replace this with "github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource"

2025-02-05 12:38 UTC, acch commented on internal/provider/svm/svm_qos_policy_activation_resource_test.go
> +	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
Sure - done. Sorry, must have missed that.

2025-02-05 20:50 UTC, suhasbshekar commented
Please resolve the conflicts.

2025-02-05 20:50 UTC, suhasbshekar commented
Please resolve the conflicts.

2025-02-06 19:04 UTC, acch commented
@suhasbshekar I've rebased the PR once again.

Can you please let me know when you'll be able to merge these changes?

2025-02-10 22:57 UTC, suhasbshekar commented
conflicts

2025-02-10 23:01 UTC, suhasbshekar commented
Also can you fix  the lint issue which was caused from merging the previous PR?
`Error: internal/provider/networking/network_ip_interface_resource_test.go:15:7: idRegex redeclared in this block
Error: 	internal/provider/networking/network_ethernet_port_resource_test.go:15:7: other declaration of idRegex (compile)
Error: Process completed with exit code 1.`

2025-02-11 10:49 UTC, acch commented
@suhasbshekar Conflicts resolved and linter errors fixed.

2025-02-11 18:24 UTC, suhasbshekar approved these changes

2025-02-11 18:31 UTC, chuyich commented on internal/interfaces/svm.go
> +	QoSPolicy      QoSPolicy           `mapstructure:"qos_policy"`
if both parameters in the QoSPolicy are omitempty, why QoSPolicy is not omitempty?

2025-02-11 19:43 UTC, acch commented on internal/interfaces/svm.go
> +	QoSPolicy      QoSPolicy           `mapstructure:"qos_policy"`
@chuyich Based on my testing, `omitempty` does not have any effect on attributes of type struct (such as `Ipspace` or `QoSPolicy`). It removes strings and numbers from the request body, but not structs.

2025-02-11 21:33 UTC, merged